// Deterministic seed generator → writes data/test.sql.
// Fixed PRNG seed = reproducible output (golden guide stays stable for grading).
// Run: node scripts/gen-seed.mjs   (tweak COUNTS below to scale)
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const COUNTS = { procedures: 200, guides: 500, payers: 5, routes: 5 };

function mulberry32(a) {
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rnd = mulberry32(42);
const pick = (arr) => arr[Math.floor(rnd() * arr.length)];
const int = (min, max) => min + Math.floor(rnd() * (max - min + 1));

const ROUTES = [
  ["route-a", "Anterior"],
  ["route-b", "Posterior"],
  ["route-c", "Lateral"],
  ["route-d", "Endoscopica"],
  ["route-e", "Percutanea"],
];
const PAYERS = [
  ["payer-x", "Convênio X"],
  ["payer-y", "Convênio Y"],
  ["payer-z", "Convênio Z"],
  ["payer-w", "Convênio W"],
  ["payer-v", "Convênio V"],
];
const PCT_POOL = ["[100,70,50]", "[100,50]", "[100,75,50,50]", "[100,60,40]"];
const PROC_NAMES = [
  "Artrodese", "Tenotomia", "Sutura de tendao", "Radiografia", "Tomografia",
  "Ressonancia", "Biopsia", "Drenagem", "Exerese de lesao", "Cauterizacao",
  "Endoscopia", "Colonoscopia", "Ultrassonografia", "Densitometria", "Mamografia",
  "Artroscopia", "Osteossintese", "Enxerto", "Reducao de fratura", "Infiltracao",
];
const FIRST = ["Joao", "Maria", "Pedro", "Ana", "Carlos", "Lucia", "Marcos", "Beatriz", "Rafael", "Juliana"];
const LAST = ["Silva", "Souza", "Oliveira", "Santos", "Pereira", "Lima", "Costa", "Almeida", "Ribeiro", "Gomes"];

const lines = [];
const emitRows = (table, cols, rows) => {
  if (!rows.length) return;
  lines.push(`INSERT INTO ${table} (${cols.join(", ")}) VALUES`);
  rows.forEach((r, i) => lines.push(`  (${r.join(", ")})${i === rows.length - 1 ? ";" : ","}`));
  lines.push("");
};
const s = (v) => (v === null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);

lines.push("-- Generated by scripts/gen-seed.mjs (deterministic seed). Apply after schema.sql.");
lines.push("-- Your logic must price ANY guide correctly.");
lines.push("");

// ── routes & payers ──────────────────────────────────────────────────────────
emitRows("access_routes", ["id", "name"], ROUTES.map(([id, n]) => [s(id), s(n)]));
emitRows("payers", ["id", "name"], PAYERS.map(([id, n]) => [s(id), s(n)]));

// ── rules: default + one per payer (payer-x is fixed [100,50] for the golden case)
const rules = [["default", null, "[100,70,50]", "accessRoute"]];
PAYERS.forEach(([id], i) =>
  rules.push([id, id, id === "payer-x" ? "[100,50]" : pick(PCT_POOL), "accessRoute"]),
);
emitRows("pricing_rules", ["id", "payer_id", "reduction_pct", "group_by"],
  rules.map(([id, payer, pct, gb]) => [s(id), s(payer), s(pct), s(gb)]));

// ── procedures: 4 golden (fixed) + bulk ───────────────────────────────────────
const GOLDEN_PROCS = [
  ["30602246", "Artrodese de grande articulacao", 80000, "route-a"],
  ["30602050", "Tenotomia", 33333, "route-a"],
  ["30715016", "Sutura de tendao", 33333, "route-a"],
  ["40808152", "Radiografia", 30000, "route-b"],
];
const procs = [...GOLDEN_PROCS];
const usedTuss = new Set(GOLDEN_PROCS.map((p) => p[0]));
let nextTuss = 40000000;
while (procs.length < COUNTS.procedures) {
  const code = String(nextTuss++);
  if (usedTuss.has(code)) continue;
  usedTuss.add(code);
  procs.push([code, `${pick(PROC_NAMES)} ${code.slice(-4)}`, int(50, 1500) * 100 + int(0, 99), pick(ROUTES)[0]]);
}
emitRows("procedures", ["tuss_code", "description", "base_value_cents", "access_route_id"],
  procs.map((p) => [s(p[0]), s(p[1]), p[2], s(p[3])]));

// ── guides: golden guide 1 (fixed) + bulk ─────────────────────────────────────
const guides = [[1, "Joao da Silva"]];
const items = [
  [1, 1, 1, "30602246", 1, null],
  [2, 1, 2, "30602050", 1, null],
  [3, 1, 3, "30715016", 1, null],
  [4, 1, 4, "40808152", 2, null],
];
let itemId = 5;
for (let g = 2; g <= COUNTS.guides; g++) {
  guides.push([g, `${pick(FIRST)} ${pick(LAST)}`]);
  const n = int(1, 6);
  for (let pos = 1; pos <= n; pos++) {
    const proc = pick(procs);
    const qty = rnd() < 0.2 ? int(2, 3) : 1;
    const override = rnd() < 0.1 ? int(50, 1500) * 100 : null;
    items.push([itemId++, g, pos, proc[0], qty, override]);
  }
}
emitRows("guides", ["id", "patient_name"], guides.map((g) => [g[0], s(g[1])]));
emitRows("guide_items", ["id", "guide_id", "position", "tuss_code", "qty", "base_value_override_cents"],
  items.map((it) => [it[0], it[1], it[2], s(it[3]), it[4], it[5] === null ? "NULL" : it[5]]));

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "data", "test.sql");
writeFileSync(out, lines.join("\n") + "\n");
console.log(`✓ ${out} — ${procs.length} procedures, ${guides.length} guides, ${items.length} items`);
